name: "Connect-Smart V1"
version: "0.1"
slug: "connect_smart_v1"
description: "Dit is versie 1"
homeassistant_api: true
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: "application"
boot: "auto"
options:
  username: "Connect-Smart"
  password: ""
  cheapest_energy_automation: ""
  most_expensive_energy_automation: ""
  schedule: "17:35:21"
schema:
  username: "str"
  password: "password"
  cheapest_energy_automation: "str"
  most_expensive_energy_automation: "str"
  schedule: "str"
map:
  - config:rw
  - share:rw
  - addon_config:rw
ports:
  "8080/tcp": 8080
ingress: true
ingress_port: 8080
ingress_panel: true
ingress_url: "/connect_smart_v1"
ingress_category: addon
ingress_stream: true
ingress_entry: "admin"
ingress_entry: "ingress"
ingress_entry: "about"
#ingress_entry: "admin"
#ingress_domain: "connect_smart_v1"
