name: "Connect-Smart V1"
version: "0.1"
slug: "connect_smart_v1"
description: "Dit is versie 1."
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: "application"
boot: "auto"
options: {}
schema: {}
ports:
  "8080/tcp": 8080
panel: true  
python_packages:
  - requests==2.25.1
  - Flask==1.1.2
